from io import StringIO
import sys


old_stdout = sys.stdout
sys.stdout = mystdout = StringIO()

#INJECT-b585472fa

sys.stdout = old_stdout

if "negative_odd_sum" not in globals():
    print("Function negative_odd_sum() doesn't exist")
    exit(1)

if not callable(negative_odd_sum):
    print("'negative_odd_sum' is not a function")
    exit(1)

tests = [
    ["a", 1, TypeError],
    [1, {"a": "b"}, TypeError],
    [3.4, True, TypeError],
    [4, -1, ValueError],
    [-2, 8, ValueError],
    [7, 9, ValueError],
    [-7, -9, -16],
    [-8, 3, ValueError],
    [5, -11, ValueError],
    [-13, -13, -26],
    [-1, -3, -4]]

for test in tests:
    a, b, res_plan = test
    throws = not isinstance(res_plan, int)
    try:
        res_fact = negative_odd_sum(a, b)
        if res_fact != res_plan:
            print(f"Function output is invalid for input: {a}, {b}")
            exit(1)
    except Exception as e:
        if not throws:
            print(f"Function 'negative_odd_sum()' raises exception for input: {a}, {b}")
            exit(1)

        if not isinstance(e, res_plan):
            print(f"Function 'negative_odd_sum()' raises invalid exception type for input: {a}, {b}")
            exit(1)

        continue

    if throws:
        print(f"Function `negative_odd_sum()` doesn't raise exception for input: {a}, {b}")
        exit(1)
    

